### ISSUE TITLE
Creating tags doesn't work

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/discord-mods-bot#16]
I tried to create a tag in `#meta`, and it didn't work at all.
<img width="635" alt="Screenshot 2020-03-06 at 10 32 28" src="https://user-images.githubusercontent.com/4464295/76071010-cd753d80-5f95-11ea-8ca4-cac485d26ec2.png">

**Comment by technetos** [comment]
Instead of `?tag create source url` it needs to be `?tag create source "url"`.

**Comment by khionu** [comment]
That's a little less intuitive than taking everything at the end
