### ISSUE TITLE
Sync roles with rust-lang/team

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/discord-mods-bot#24]
A lot of people's roles on the discord are out of date. It would be nice if it could sync with the rust-lang/team data.

### Proposed solution

- [ ] Add `discord-map.json` (similar to [zulip-map.json]) to the `rust-lang/team` static API that maps GitHub ids to discord ids.
- [ ] Add functionality to the bot to add labels based on team data from [teams.json].
- [ ] Later remove labels from people that aren't members of the team, once people have had enough time to make sure their discord is in `rust-lang/team`.

[zulip-map.json]: https://team-api.infra.rust-lang.org/v1/zulip-map.json
[teams.json]: https://team-api.infra.rust-lang.org/v1/teams.json

**Comment by khionu** [comment]
Maybe a daily sync? Seems easy enough.
