### ISSUE TITLE
Add `?docs` command

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/discord-mods-bot#31]
Similar to the `?crate`, it would be nice to be able to link to docs.rs using a command.

**Comment by tinaun** [comment]
should ?docs search for the argument first, or just always return `https://docs.rs/{argument}` directly without searching? im thinking of adding `?issue number` and `?rfc number` that just concatenate `https://github.com/rust-lang/rust/ + number`

**Comment by XAMPPRocky** [comment]
Well I would expect a mention of a valid crate e.g. `?docs tokei` to link directly to its docs, I don’t really know what would be the best behaviour beyond that.

**Comment by khionu** [comment]
I would personally prefer verification.
