### ISSUE TITLE
Add `std` command

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/discord-mods-bot#37]
Currently we have a `?docs` command for docs.rs but I've seen people try to use it to look standard lib documentation. I think it would nice to also have a command to pull up stdlib documentation.

**Comment by khionu** [comment]
"Good first issue" because it's not a command that needs a look up, but would print a statically generated embed.

**Comment by kangalioo** [comment]
Well this issue can be closed now, right? For example you can write `?docs std::io::Error` and it will bring up the standard library documentation.

**Comment by khionu** [comment]
Indeed, thank you!
