### ISSUE TITLE
argument parsing can never match on non ascii strings 

### ISSUE THREAD

**Issue by tinaun** [rust-lang/discord-mods-bot#64]
specifically, CharacterSet is defined to work only for values between 0 and 127 - this prevents non ASCII characters from being used in commands (which is admittedly pretty unlikely to ever come up in the rust server).

the more pressing issue is that the charset created from CharacterSet::any() does not match any character, only ascii ones, so commands that take rust code like ?play silently fail if given valid rust code that just happens to contain non-ascii characters

**Comment by technetos** [comment]
This is somewhat intentional.  I do not intend to support non-ascii commands.
