### ISSUE TITLE
?play and ?eval erroneously claim that the code block is missing when there is content after the code block

### ISSUE THREAD

**Issue by PatchMixolydic** [rust-lang/discord-mods-bot#84]
<img src="https://user-images.githubusercontent.com/8634700/118361811-982d8d80-b552-11eb-9862-b422b5593d47.png" alt ="Screenshot of rustbot on Discord. I send '?eval `Box::new(Vec::new())` text after', to which rustbot replies 'Missing code block. ...' I then send '?play ```rust fn main() {} ``` text after', and again, rustbot replies 'Missing code block. ...'" width=600>

This is a fairly minor nitpick, but the message is inaccurate since code blocks are present in both cases. This message might cause confusion for someone who doesn't realize that their message must end after the code block.

**Comment by khionu** [comment]
Commands don't allow for arguments in excess of what they expect. This could be accounted for, but it would be odd for commands like our `?ban`, which takes a reason of arbitrary length as the last argument.

**Comment by technetos** [comment]
Actually, if we add another variant of the command for play and eval to accept any text after the code block these would be recognized.

**Comment by PatchMixolydic** [comment]
Ignoring any text after the code block could be marginally useful for explaining code examples in the #beginners and #rust-usage sections of the The Rust Programming Language Discord server. An alternative (which is what I was originally thinking of but failed to communicate) would be to emit a different error message for this case explaining that `?play` and `?eval` expect nothing to follow the code block, though I'm not sure how feasible this is.

**Comment by technetos** [comment]
@PatchMixolydic #85

**Comment by khionu** [comment]
This is easy enough to do by typing it all out, then copying the comment and sending it _after_ the command, using `println!` to comment the output. Slash commands, which we probably will switch to in the future, would complicate this addition.

Aside from `println!`, what we could do is add an API within the boilerplate we send to the Playground that would allow customizing the output of the command. In short, the stdout would become a JSON blob augmented by the API we create, and then we can format the command output by that blob. We could start by replacing `println!` and `print!` with our own macros.

Just to note the more specific idea while I have it, another feature would be lined outputs. Ie, the bot could provide this at the output:
```rs
pub fn main() {
    println!("42");     // Output: 42
}
```
Loops may complicate this, but I think it's well within the realm of possibilities.
