### ISSUE TITLE
Reserve output for ?play and ?eval immediately after seeing them

### ISSUE THREAD

**Issue by alexschrod** [rust-lang/discord-mods-bot#86]
It's a bit jarring and frustrating when you make a ?play or ?eval command, and then somebody else writes a message while the bot waits for the playground to finish running the code, so the input message gets separated from the output message.

If the bot instead, upon seeing ?play or ?eval immediately reserved room for the response by immediately writing a reply (Something like "running, please wait..." or whatever is appropriate) which it then edits once the response comes back, this awkwardness could be a thing of the past.

I feel like this shouldn't be too hard to do, especially given how well the bot already handles re-executing edited messages in the same response message or deleting response messages upon the deletion of the ?play/?eval message—clearly the bot is already tracking message/response associations.

**Comment by technetos** [comment]
I think this is a great idea.
